<?php

/**
 * Returns a link to the next weighted node of the same draggable view
 *
 * @current_nid, int
 *   - The current nid
 * @draggable_view_name, string
 *   - The name of the draggableviews view used to order the nodes
 * @display, string (optional)
 *   - The link display
 */
function bx_next_link($current_nid, $draggable_view_name, $display = 'Next'){
	$results = views_get_view_result('gowns', 'page_1');
	$nids = array();
	foreach ($results as $result) {
		$nids[] = $result->nid;
	}
	$current_index = array_search($current_nid, $nids);
	$next_nid = $current_index == count($results) - 1 ? $results[0]->nid : $results[$current_index + 1]->nid;
	return '<a class="next" href="/' . drupal_get_path_alias('node/' . $next_nid) . '">' . $display . '</a>';
}

/**
 * Returns a link to the previous weighted node of the same draggable view
 *
 * @current_nid, int
 *   - The current nid
 * @draggable_view_name, string
 *   - The name of the draggableviews view used to order the nodes
 * @display, string (optional)
 *   - The link display
 */
function bx_prev_link($current_nid, $draggable_view_name, $display = 'Previous'){
	$results = views_get_view_result('gowns', 'page_1');
	$nids = array();
	foreach ($results as $result) {
		$nids[] = $result->nid;
	}
	$current_index = array_search($current_nid, $nids);
	$prev_nid = $current_index == 0 ? $results[count($results) - 1]->nid : $results[$current_index - 1]->nid;
	return '<a class="prev" href="/' . drupal_get_path_alias('node/' . $prev_nid) . '">' . $display . '</a>';
}